# Generated by Django 5.0 on 2023-12-08 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghost', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='image_status',
            field=models.ImageField(default='media/default.jpeg', upload_to='user/', validators=[django.core.validators.validate_image_file_extension, django.core.validators.FileExtensionValidator(['bmp', 'jpeg', 'jpg', 'png'], message='Allowed types: bmp, jpeg, jpg. png')], verbose_name='Image for status'),
        ),
    ]
